// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * Click here to upload
		 */
		clickHereToUpload: string
		/**
		 * User
		 */
		user: string
		/**
		 * Users
		 */
		users: string
		/**
		 * Name
		 */
		name: string
		/**
		 * First name
		 */
		firstName: string
		/**
		 * Full name
		 */
		fullName: string
		/**
		 * Middle name
		 */
		middleName: string
		/**
		 * Middle names
		 */
		middleNames: string
		/**
		 * Nickname
		 */
		nickname: string
		/**
		 * Email
		 */
		email: string
		/**
		 * Password
		 */
		password: string
		/**
		 * Login
		 */
		login: string
		/**
		 * Logout
		 */
		logout: string
		/**
		 * Settings
		 */
		settings: string
		/**
		 * History
		 */
		history: string
		/**
		 * Section name
		 */
		sectionName: string
		/**
		 * Home page
		 */
		homePage: string
		/**
		 * Useful links
		 */
		usefulLinks: string
		/**
		 * Top
		 */
		top: string
		/**
		 * Non responsive
		 */
		nonResponsive: string
		/**
		 * It's not mobile friendly
		 */
		nonResponsive2: string
		/**
		 * You are opening a link to an external website
		 */
		openingExternalWebsite: string
		/**
		 * Open the website
		 */
		openTheWebsite: string
		/**
		 * Do not open
		 */
		doNotOpen: string
		/**
		 * This site, for now, is just a layout example.
		 */
		warningMessage: string
		/**
		 * Note: The site is just a layout example, it is not possible to change the data.
		 */
		warningMessage2: string
		/**
		 * This site, for now, is just an example of a layout under development. No form content will be saved and many functional and visual changes will still be made.
		 */
		warningMessage3: string
		/**
		 * This site, for now, is just an example of a layout in the development stage. Many functional and visual changes are yet to be made.
		 */
		warningMessage4: string
		/**
		 * The final version of this page will be TOTALLY different from this example.
		 */
		warningMessage5: string
	}
	language: {
		/**
		 * Language
		 */
		language: string
		/**
		 * Languages
		 */
		languages: string
		/**
		 * English
		 */
		en: string
		/**
		 * Portuguese
		 */
		pt: string
		originalName: {
			/**
			 * English
			 */
			en: string
			/**
			 * Português
			 */
			pt: string
		}
		/**
		 * Language settings
		 */
		languageSettings: string
		/**
		 * Choose a language
		 */
		chooseALanguage: string
		/**
		 * Below are the translation options provided by the platform. Choose your preferred language.
		 */
		messageToChooseLanguage: string
		/**
		 * Confirm language choice
		 */
		confirmLanguageChoice: string
	}
	theme: {
		/**
		 * Theme
		 */
		theme: string
		/**
		 * Themes
		 */
		themes: string
		themeName: {
			/**
			 * Default
			 */
			'default': string
			/**
			 * Potato
			 */
			'light-potato': string
			/**
			 * Reptilian
			 */
			'light-reptilian': string
		}
		themeMessage: {
			/**
			 * The most beautiful theme in the galaxy
			 */
			'default': string
			/**
			 * This theme is delicious
			 */
			'light-potato': string
			/**
			 * A theme from another planet
			 */
			'light-reptilian': string
		}
		/**
		 * Theme settings
		 */
		themeSettings: string
		/**
		 * Theme in use
		 */
		themeInUse: string
		/**
		 * Current
		 */
		current: string
		/**
		 * Themes available
		 */
		themesAvailable: string
	}
	menu: {
		/**
		 * Menu
		 */
		menu: string
		/**
		 * Platform settings
		 */
		adminSettings: string
		/**
		 * Feedback
		 */
		feedback: string
		/**
		 * History
		 */
		activitiesHistory: string
		/**
		 * All users
		 */
		platformUsers: string
		/**
		 * Topics
		 */
		topics: string
		/**
		 * Invitations
		 */
		invitations: string
		/**
		 * User settings
		 */
		userSettings: string
		/**
		 * Polls
		 */
		polls: string
		/**
		 * Memorandum
		 */
		memorandum: string
		/**
		 * Logout
		 */
		logout: string
		/**
		 * News
		 */
		news: string
	}
	accounts: {
		/**
		 * Account
		 */
		account: string
		/**
		 * Accounts
		 */
		accounts: string
		/**
		 * Privileges
		 */
		privileges: string
		/**
		 * Account types
		 */
		accountTypes: string
		/**
		 * About platform accounts
		 */
		aboutPlatformAccounts: string
		/**
		 * Platform account types
		 */
		platformAccountTypes: string
		/**
		 * Users can have different types of accounts. These types of accounts exist to facilitate access and management of the platform. The existing account types are as follows:
		 */
		platformAccountTypesMessage: string
		/**
		 * Extra privileges for full members
		 */
		extraPrivilegesForFullMembers: string
		/**
		 * All "<b>Full Member</b>" accounts can gain some extra privileges attached to them, the following privileges:
		 */
		extraPrivilegesForFullMembersMessage: string
		accountType: {
			/**
			 * Admin
			 */
			admin: string
			/**
			 * Maintainer
			 */
			maintainer: string
			/**
			 * Developer
			 */
			developer: string
			/**
			 * Full member
			 */
			fullMember: string
			/**
			 * Partner member
			 */
			partnerMember: string
			/**
			 * Guest
			 */
			guest: string
		}
		accountDescription: {
			/**
			 * This is the most privileged type of account, aimed at lifetime members.
			 */
			fullMember: string
			/**
			 * This is an account type aimed at users who have some kind of relationship with a full member.
			 */
			partnerMember: string
			/**
			 * Account aimed at a guest user who knows someone on the platform.
			 */
			guest: string
		}
		privilegeType: {
			/**
			 * Administrator
			 */
			administrator: string
			/**
			 * Mature age
			 */
			matureAge: string
			/**
			 * Developer
			 */
			developer: string
		}
		privilegeDescription: {
			/**
			 * This is a privilege that allows a user to change platform settings.
			 */
			administrator: string
			/**
			 * Member old enough to be considered a mature user to handle choices that require more responsibility.
			 */
			matureAge: string
			/**
			 * Members who have fulfilled the necessary prerequisites to change the platform code.
			 */
			developer: string
		}
		/**
		 * Full member account
		 */
		fullMemberAccount: string
		/**
		 * Your account type
		 */
		yourAccountType: string
		/**
		 * You have an account of the type
		 */
		youHaveAnAccountOfTheType: string
	}
	activities: {
		/**
		 * Activity
		 */
		activity: string
		/**
		 * Activities
		 */
		activities: string
		/**
		 * Activity history
		 */
		activityHistory: string
		/**
		 * Latest activities on the platform
		 */
		latestActivitiesOnThePlatform: string
		activityName: {
			/**
			 * Created feedback
			 */
			createdFeedback: string
			/**
			 * Created memorandum
			 */
			createdMemo: string
			/**
			 * Created news
			 */
			createdNews: string
			/**
			 * Created poll
			 */
			createdPoll: string
		}
	}
	feedback: {
		exampleOne: {
			/**
			 * A pink button could be created
			 */
			title: string
			/**
			 * I find the color of the platform buttons very ugly, so I suggest a color change. I think there should be a possibility for users to choose the color of their buttons in the settings. I would love to be able to click pink buttons.
			 */
			message: string
			/**
			 * This idea is cool. Will any developer be able to solve this issue?
			 */
			answerOne: string
			/**
			 * I really liked this idea too. I'll try to implement the code for this pink button, but it seems too complicated, I don't know if I'll be able to.
			 */
			answerTwo: string
		}
		exampleTwo: {
			/**
			 * New functionality to register family tree?
			 */
			title: string
			message: string
		}
		exampleThree: {
			/**
			 * Spelling error on the home page
			 */
			title: string
			message: string
		}
		exampleFour: {
			/**
			 * Can we create our version of Netflix?
			 */
			title: string
			message: string
		}
		/**
		 * Feedback
		 */
		feedback: string
		/**
		 * Would you like to share your opinion? Any suggestions for the platform? If yes,
		 */
		description: string
		/**
		 * post your comment here
		 */
		postYourCommentHere: string
		/**
		 * Create feedback
		 */
		createFeedback: string
		/**
		 * Manage feedback
		 */
		manageFeedback: string
		/**
		 * Create feedback about the platform
		 */
		createFeedbackAboutThePlatform: string
		/**
		 * Create feedback about the platform to send to the members. This feedback can be feature suggestions, reports of malfunctions, and opinions.
		 */
		createFeedbackAboutThePlatformMessage: string
		/**
		 * Title of your feedback
		 */
		titleOfYourFeedback: string
		/**
		 * Messages
		 */
		messages: string
		/**
		 * Write message
		 */
		writeMessage: string
		/**
		 * Answer
		 */
		answer: string
		/**
		 * Message
		 */
		message: string
		/**
		 * Please write your message below, and if possible, include a large amount of data and details in your content, so that we can handle and understand the information in the best possible way.
		 */
		messageMessage: string
		/**
		 * Send feedback
		 */
		sendFeedback: string
		/**
		 * Feedback management
		 */
		feedbackManagement: string
		/**
		 * Author
		 */
		author: string
		/**
		 * By
		 */
		by: string
		/**
		 * Last interaction
		 */
		lastInteraction: string
		/**
		 * Publication date
		 */
		publicationDate: string
		/**
		 * There is only one example of feedback on the platform, the following:
		 */
		justOneExample: string
		/**
		 * Would you like to open this example?
		 */
		wouldYouLikeToOpenThisExample: string
		/**
		 * Open the example
		 */
		openTheExample: string
		/**
		 * Do not open
		 */
		doNotOpenTheExample: string
		/**
		 * Feedback created ✌
		 */
		feedbackCreated: string
		/**
		 * Your feedback has been sent to platform members
		 */
		feedbackCreatedMessage: string
		/**
		 * What would you like to do now?
		 */
		whatWouldYouLikeToDoNow: string
		/**
		 * Create new feedback
		 */
		createNewFeedback: string
		/**
		 * Go to home page
		 */
		goToHomePage: string
	}
	forms: {
		userTypesWithAccess: {
			/**
			 * Account types that can access content
			 */
			title: string
			/**
			 * "{mainAccountType}" accounts can view all content on the platform, however, for other types of accounts it is necessary to grant access. Select below which accounts you want to grant access to the content:
			 * @param {string} mainAccountType
			 */
			message: RequiredParams<'mainAccountType'>
		}
	}
	homePage: {
		headerMessageExample: {
			/**
			 * What will the child be called?
			 */
			title: string
			/**
			 * I have just published a poll on the platform, where you can suggest the name of John's and mine's son. If the name you suggested is chosen, in addition to the honor of this choice, you will also win a <b>super gift</b>! 🎉
			 */
			description: string
			/**
			 * Jane Doe - @jane
			 */
			author: string
		}
		sections: {
			/**
			 * Platform sections
			 */
			title: string
			/**
			 * User settings
			 */
			userSettings: string
			/**
			 * Polls and answers
			 */
			polls: string
			/**
			 * Group topics
			 */
			topics: string
			/**
			 * All users
			 */
			users: string
			/**
			 * Group newspaper
			 */
			newsReader: string
			/**
			 * Invitations management
			 */
			invitations: string
			/**
			 * Feedback management
			 */
			feedback: string
			/**
			 * Platform settings
			 */
			platformSettings: string
			/**
			 * Activities history
			 */
			activitiesHistory: string
			/**
			 * Memorandum
			 */
			memorandum: string
		}
		polls: {
			/**
			 * Published polls
			 */
			title: string
		}
		memos: {
			/**
			 * Memorandum
			 */
			title: string
		}
		lastNews: {
			/**
			 * Last news - {newsReaderName}
			 * @param {string} newsReaderName
			 */
			title: RequiredParams<'newsReaderName'>
		}
		topics: {
			/**
			 * Group topics
			 */
			title: string
		}
	}
	invitations: {
		/**
		 * Invitations
		 */
		invitations: string
		request: {
			/**
			 * Invitation request
			 */
			invitationRequest: string
			/**
			 * Request an invitation so you can register on the platform.
			 */
			invitationMessage: string
			/**
			 * Name
			 */
			name: string
			/**
			 * Email
			 */
			email: string
			/**
			 * Message
			 */
			message: string
			/**
			 * Return
			 */
			'return': string
			/**
			 * Request invitation
			 */
			requestInvitation: string
			/**
			 * Congratulations!
			 */
			congratulations: string
			/**
			 * Your invitation has been approved
			 */
			invitationApproved: string
			/**
			 * The invitation for you to become a member of the platform has been approved. Now <b>the next step is to resolve the pending issues</b> of your registration. Click on the button below to view your pending issues.
			 */
			pendingIssuesMessage: string
			/**
			 * Go to registration issues
			 */
			goToRegistrationIssues: string
		}
		requestsReceived: {
			/**
			 * Requests
			 */
			requests: string
			/**
			 * Recent invite requests
			 */
			recentInviteRequests: string
			/**
			 * Pending invite requests
			 */
			pendingInviteRequests: string
			/**
			 * Approved invite requests
			 */
			approvedInviteRequests: string
			/**
			 * Rejected invite requests
			 */
			rejectedInviteRequests: string
			/**
			 * Request date
			 */
			requestDate: string
			/**
			 * Approval date
			 */
			approvalDate: string
			/**
			 * Rejection date
			 */
			rejectionDate: string
			/**
			 * Name
			 */
			name: string
			/**
			 * Request message
			 */
			requestMessage: string
			/**
			 * Approved by
			 */
			approvedBy: string
			/**
			 * Rejected by
			 */
			rejectedBy: string
			/**
			 * Account type given
			 */
			accountTypeGiven: string
			/**
			 * Justification
			 */
			justification: string
			examples: {
				/**
				 * Hi family! Please accept my request.
				 */
				pendingMessageOne: string
				/**
				 * I'm Jane's friend, and I would like a "guest account" so that I can answer my friend's polls. Thanks! :)
				 */
				pendingMessageTwo: string
				/**
				 * Hey guys! Accept my request.
				 */
				approvedMessageOne: string
				/**
				 * I don't like this guy
				 */
				rejectedJustificationOne: string
				/**
				 * Hey! I would like to be part of your group.
				 */
				rejectedMessageOne: string
			}
		}
		sendInvitation: {
			/**
			 * Send invitation
			 */
			sendInvitation: string
			/**
			 * Name of person to be invited
			 */
			nameOfPersonToBeInvited: string
			/**
			 * Email of person to be invited
			 */
			emailOfPersonToBeInvited: string
			/**
			 * Message
			 */
			message: string
			/**
			 * Invitation sent ✌
			 */
			invitationSent: string
			/**
			 * Your invitation has been sent successfully
			 */
			invitationSentMessage: string
			/**
			 * What would you like to do now?
			 */
			whatWouldYouLikeToDoNow: string
			/**
			 * Go to invitation management
			 */
			goToInvitationManagement: string
			/**
			 * Go to home page
			 */
			goToHomePage: string
		}
		invitationsSent: {
			/**
			 * Invitations sent
			 */
			invitationsSent: string
			/**
			 * Recently sent invitations
			 */
			recentlySentInvitations: string
			/**
			 * Sent date
			 */
			sentDate: string
			/**
			 * Sent by
			 */
			sentBy: string
			/**
			 * Sent to
			 */
			sentTo: string
			/**
			 * Message
			 */
			message: string
			example: {
				/**
				 * Hey friend! Come be part of my family's platform.
				 */
				message: string
			}
		}
	}
	memos: {
		/**
		 * Memorandum
		 */
		memos: string
		/**
		 * Memorandum
		 */
		memorandum: string
		exampleOne: {
			/**
			 * 18.jun.2022
			 */
			date: string
			/**
			 * Jane's trip scheduled
			 */
			title: string
			/**
			 * Published on June 18, 2022.
			 */
			publishedOn: string
			/**
			 * Dear Family
			 */
			dearFamily: string
			/**
			 * I just bought my plane ticket to Brazil. I will arrive at the airport in Porto Alegre/RS, on the 23rd of July, at 10 am.
			 */
			paragraphOne: string
			/**
			 * And the next day, the 24th, I would like to meet with the whole family at grandma Eliza Doe's house. So book a space in your calendar.
			 */
			paragraphTwo: string
			/**
			 * With love
			 */
			kindRegards: string
			/**
			 * Note: I'm taking some sweets and gifts that I'm going to give to everyone who comes to see me at grandma Eliza's house.
			 */
			note: string
		}
		exampleTwo: {
			/**
			 * 02.jun.2022
			 */
			date: string
			/**
			 * Next Doe Family reunion
			 */
			title: string
		}
		/**
		 * Go to memos
		 */
		goToMemos: string
		/**
		 * Go to home page
		 */
		goToHomePage: string
		warningMessage: {
			/**
			 * There is only one memorandum example on the platform, the following:
			 */
			onlyOneExample: string
			/**
			 * Would you like to open this example?
			 */
			wouldYouLikeToOpenThisExample: string
			/**
			 * Open the example
			 */
			openTheExample: string
			/**
			 * Do not open
			 */
			doNotOpen: string
		}
		/**
		 * Memos management
		 */
		memoManagement: string
		/**
		 * A memo is a practical communication and record, in text format, on some relevant subject. Here in this section it is possible to create memos to send to all members of the platform, and also, it is possible to read memos previously sent.
		 */
		memoManagementMessage: string
		/**
		 * Create memo
		 */
		createMemo: string
		/**
		 * Show all memos
		 */
		showAllMemos: string
		/**
		 * Show recent memos only
		 */
		showRecentMemos: string
		/**
		 * All memos
		 */
		allMemos: string
		/**
		 * Recent memos
		 */
		recentMemos: string
		/**
		 * Memo created 🎉
		 */
		memoCreated: string
		/**
		 * Your memo has been created and sent to members
		 */
		memoCreatedMessage: string
		/**
		 * What do you want to do now?
		 */
		whatDoYouWantToDoNow: string
		/**
		 * Title
		 */
		title: string
		/**
		 * Message
		 */
		message: string
		/**
		 * Create and send memo
		 */
		createAndSendMemo: string
	}
	news: {
		exampleOne: {
			/**
			 * What will the child be called?
			 */
			title: string
		}
		exampleTwo: {
			/**
			 * Alicia has a new crush! 😱
			 */
			title: string
		}
		exampleThree: {
			/**
			 * David wins swimming gold medal
			 */
			title: string
		}
		/**
		 * News
		 */
		news: string
		/**
		 * There is only one example of news on the platform, the following:
		 */
		thereIsOnlyOneExample: string
		/**
		 * Would you like to open this example?
		 */
		wouldYouLikeToOpen: string
		/**
		 * Where would you like to open this news?
		 */
		whereOpenNewsMessage: string
		/**
		 * Open on this platform
		 */
		openOnThisPlatform: string
		/**
		 * On this platform
		 */
		onThisPlatform: string
		/**
		 * Do not open
		 */
		doNotOpen: string
		/**
		 * News data
		 */
		newsData: string
		/**
		 * Posted on
		 */
		postedOn: string
		/**
		 * Last updated
		 */
		lastUpdated: string
		/**
		 * Go to
		 */
		goTo: string
		/**
		 * Go to news section
		 */
		goToNewsSection: string
		/**
		 * Go to home page
		 */
		goToHomePage: string
		/**
		 * Suggest changes to the news
		 */
		suggestChangesToTheNews: string
		/**
		 * Read this news at
		 */
		readThisNewsAt: string
		/**
		 * Author
		 */
		author: string
		/**
		 * What would you like to do now
		 */
		whatWouldYouLikeToDoNow: string
		suggestChange: {
			/**
			 * Suggest news change
			 */
			suggestNewsChange: string
			/**
			 * Target news
			 */
			targetNews: string
			/**
			 * Title
			 */
			title: string
			/**
			 * Please describe your proposed amendment in detail below.
			 */
			describeMessage: string
			/**
			 * Send suggestion
			 */
			sendSuggestion: string
			/**
			 * Suggestion sent
			 */
			suggestionSent: string
			/**
			 * Your suggestion has been sent to the author of the news.
			 */
			suggestionSentMessage: string
			/**
			 * Back to previous news
			 */
			backToPreviousNews: string
		}
		/**
		 * Posted
		 */
		posted: string
		/**
		 * New/drafts
		 */
		newAndDrafts: string
		/**
		 * Scheduled
		 */
		scheduled: string
		/**
		 * News from
		 */
		newsFrom: string
		/**
		 * Next edition
		 */
		nextEdition: string
		/**
		 * <b>July 5</b>, 2022
		 */
		nextEditionDate: string
		/**
		 * Periodicity
		 */
		periodicity: string
		/**
		 * Every 40 days
		 */
		periodicityValue: string
		/**
		 * You have <b>no</b> news scheduled
		 */
		noNewsScheduled: string
		/**
		 * Edition
		 */
		edition: string
		/**
		 * Create news/draft
		 */
		createNewDraft: string
		/**
		 * Drafts
		 */
		drafts: string
		/**
		 * You have no drafts
		 */
		noDrafts: string
		/**
		 * Scheduled news
		 */
		scheduledNews: string
		/**
		 * You have no news scheduled for the next edition of
		 */
		noNewsScheduledMessage: string
		/**
		 * To create a new news go to the tab
		 */
		toCreateANewNewsGoToTheTab: string
		createNews: {
			/**
			 * News creation
			 */
			newsCreation: string
			/**
			 * Title
			 */
			title: string
			/**
			 * Image
			 */
			image: string
			mainNewsOfTheEdition: {
				/**
				 * Main news of the edition
				 */
				mainNewsOfTheEdition: string
				/**
				 * The platform's algorithm will choose only one news to be the biggest highlight of the newspaper's cover. Answer "<b>Yes</b>" if your news is a "<b>Breaking News</b>" and you want it to be considered the main news.
				 */
				mainNewsOfTheEditionMessage: string
				/**
				 * No! This news will not be the main
				 */
				notTheMainNews: string
				/**
				 * Yes! Take this news into consideration
				 */
				yesTheMainNews: string
			}
			category: {
				/**
				 * Other
				 */
				other: string
				/**
				 * Category
				 */
				category: string
				/**
				 * Sports
				 */
				sports: string
				/**
				 * Memories
				 */
				memories: string
				/**
				 * Books
				 */
				books: string
				/**
				 * Gastronomy
				 */
				gastronomy: string
				/**
				 * Series
				 */
				series: string
				/**
				 * Movies
				 */
				movies: string
				/**
				 * Music
				 */
				music: string
				/**
				 * Food
				 */
				food: string
				/**
				 * Culture
				 */
				culture: string
				/**
				 * Health
				 */
				health: string
				/**
				 * Tourism
				 */
				tourism: string
				/**
				 * Crime
				 */
				crime: string
				/**
				 * Science
				 */
				science: string
				/**
				 * Technology
				 */
				technology: string
				/**
				 * Business
				 */
				business: string
				/**
				 * Economy
				 */
				economy: string
				/**
				 * Politics
				 */
				politics: string
				/**
				 * Humor
				 */
				humor: string
				/**
				 * Meteorology
				 */
				meteorology: string
			}
			feeling: {
				/**
				 * Outro
				 */
				other: string
				/**
				 * Celebrant
				 */
				celebrant: string
				/**
				 * Passionate
				 */
				passionate: string
				/**
				 * Happy
				 */
				happy: string
				/**
				 * Funny
				 */
				funny: string
				/**
				 * Cool
				 */
				cool: string
				/**
				 * Silly
				 */
				silly: string
				/**
				 * Excited
				 */
				excited: string
				/**
				 * Energized
				 */
				energized: string
				/**
				 * Powerful
				 */
				powerful: string
				/**
				 * Peaceful
				 */
				peaceful: string
				/**
				 * Optimistic
				 */
				optimistic: string
				/**
				 * Thankful
				 */
				thankful: string
				/**
				 * Sensitive
				 */
				sensitive: string
				/**
				 * Calm
				 */
				calm: string
				/**
				 * Anxious
				 */
				anxious: string
				/**
				 * Sad
				 */
				sad: string
				/**
				 * Disappointed
				 */
				disappointed: string
				/**
				 * Angry
				 */
				angry: string
				/**
				 * Proud
				 */
				proud: string
				/**
				 * Surprised
				 */
				surprised: string
				/**
				 * Shocked
				 */
				shocked: string
				/**
				 * Confused
				 */
				confused: string
				/**
				 * Scared
				 */
				scared: string
				/**
				 * Bored
				 */
				bored: string
				/**
				 * Sick
				 */
				sick: string
				/**
				 * Seasick
				 */
				seasick: string
				/**
				 * Jealous
				 */
				jealous: string
				/**
				 * Curious
				 */
				curious: string
				/**
				 * Embarrassed
				 */
				embarrassed: string
				/**
				 * Kind
				 */
				kind: string
				/**
				 * Alert
				 */
				alert: string
				/**
				 * Investigative
				 */
				investigative: string
			}
			newsType: {
				/**
				 * Feeling
				 */
				newsType: string
				/**
				 * Choose the feeling that the content of this news fits or conveys to those who read it.
				 */
				newsTypeMessage: string
			}
			contentCharacteristics: {
				/**
				 * Content characteristics
				 */
				contentCharacteristics: string
				/**
				 * Check all the options that characterize the news content.
				 */
				contentCharacteristicsMessage: string
				/**
				 * Inappropriate for underage
				 */
				inappropriateForUnderage: string
				/**
				 * A platform member is mentioned
				 */
				aPlatformMemberIsMentioned: string
				/**
				 * The protagonist is a member of the platform
				 */
				theProtagonistIsAMemberOfThePlatform: string
			}
			whenWillBePublished: {
				/**
				 * When will the news be published?
				 */
				whenWillBePublished: string
				/**
				 * Save to drafts and do not publish
				 */
				saveToDrafts: string
				/**
				 * July 5, 2022 edition (next)
				 */
				nextEdition: string
				/**
				 * August 14, 2022 edition
				 */
				afterNextEdition: string
			}
			shortDescription: {
				/**
				 * Short description
				 */
				shortDescription: string
				/**
				 * This description may appear on the front page of the newspaper with the title of the news.
				 */
				shortDescriptionMessage: string
				/**
				 * characters typed out of {maxNumber} allowed
				 * @param {number} maxNumber
				 */
				charactersTypedMessage: RequiredParams<'maxNumber'>
			}
			/**
			 * Content
			 */
			content: string
			/**
			 * Create news
			 */
			createNews: string
			/**
			 * News created
			 */
			newsCreated: string
			/**
			 * Your news has been created successfully
			 */
			newsCreatedMessage: string
		}
		newsReader: {
			/**
			 * WARNING
			 */
			warning: string
			/**
			 * The news website you are being redirected to often reports <b>APPEALING NEWS</b> and lacks the truth, so <b>IT SHOULD NOT BE SEEN</b> by anyone.
			 */
			warningMessage: string
			/**
			 * Edition
			 */
			edition: string
			/**
			 * Redirecting in
			 */
			redirectingIn: string
			/**
			 * Posted on June 15, 2022
			 */
			postDate: string
			/**
			 * Go to platform
			 */
			goToPlatform: string
			/**
			 * By
			 */
			by: string
			example1: {
				/**
				 * <b>T</b>his page is <b>just an example to illustrate the idea</b>, but the final app will not use the technologies used here, nor will it have the same look.
				 */
				part1: string
				/**
				 * <b>T</b>he idea of this page is to create a website that looks similar to
				 */
				part2A: string
				/**
				 * from the Harry Potter saga.
				 */
				part2B: string
				/**
				 * <b>T</b>he website is intended to be used in a <b>digital panel</b> on the wall, and framed like a painting.
				 */
				part3: string
				/**
				 * <b>T</b>he current version is not mobile friendly, as it was created quickly just to exemplify the idea, but the final version could be.
				 */
				part4: string
				/**
				 * <b>T</b>he website will have many formatting features and visual effects that can be configured by the news authors.
				 */
				part5: string
				/**
				 * <b>T</b>he page will be hosted on its own domain, but will share the same backend as the main platform.
				 */
				part6: string
			}
			example2: {
				/**
				 * WHAT WILL THE CHILD BE CALLED?
				 */
				title: string
				/**
				 * <b>I</b> have just published a poll on the platform, where you can suggest the name of John's and mine's son. If the name you suggested is chosen, in addition to the honor of this choice, you will also win a <b>super gift</b>!
				 */
				part1: string
				/**
				 * <b>G</b>olden tip! Research the origin of the name before posting your suggestion. The meaning of the name is very important for parents.
				 */
				part2: string
				/**
				 * <b>N</b>ames whose meaning is <b>related to the sea</b> will be very well seen, as the parents are surfers, half hippies, and love the sea and nature.
				 */
				part3: string
				/**
				 * THE 2º PLACE
				 */
				part4SubTitle: string
				/**
				 * <b>T</b>he person who suggests the second name that the parents like the most will also be awarded!
				 */
				part4: string
				/**
				 * <b>T</b>he second place award will consist of a <b>two-week trip to the Falklands Islands</b>.
				 */
				part5: string
				/**
				 * <b>A</b>ll those who answer the poll on the platform, and guess the gender of our baby, will also win a nice award.
				 */
				part6: string
				/**
				 * <b>T</b>his award will be simple, surprise, but VERY useful!
				 */
				part7: string
				/**
				 * BOY OR GIRL?
				 */
				verticalTitle: string
			}
			example2B: {
				/**
				 * June 15, 2022
				 */
				date: string
				/**
				 * What will the child be called?
				 */
				title: string
				/**
				 * I have just published a poll on the platform, where you can suggest the name of John's and mine's son. If the name you suggested is chosen, in addition to the honor of this choice, you will also win a <b>super gift</b>!
				 */
				part1: string
				/**
				 * Golden tip! Research the origin of the name before posting your suggestion. The meaning of the name is very important for parents.
				 */
				part2: string
				/**
				 * Names whose meaning is <b>related to the sea</b> will be very well seen, as the parents are surfers, half hippies, and love the sea and nature.
				 */
				part3: string
				/**
				 * The 2º place
				 */
				part4SubTitle: string
				/**
				 * The person who suggests the second name that the parents like the most will also be awarded!
				 */
				part4: string
				/**
				 * The second place award will consist of a <b>two-week trip to the Falklands Islands</b>.
				 */
				part5: string
				/**
				 * Boy or girl?
				 */
				part6SubTitle: string
				/**
				 * All those who answer the poll on the platform, and guess the gender of our baby, will also win a nice award.
				 */
				part6: string
				/**
				 * This award will be simple, surprise, but VERY useful!
				 */
				part7: string
			}
		}
	}
	platformSettings: {
		/**
		 * Platform settings
		 */
		platformSettings: string
		generalSection: {
			/**
			 * General
			 */
			menu: string
			/**
			 * Platform settings
			 */
			title: string
			/**
			 * This settings section is only visible to the accounts of <b>admin members</b> who are considered to be <b>mature age</b>.
			 */
			message: string
			/**
			 * Age of a mature member
			 */
			ageOfAMatureMember: string
			/**
			 * Set the minimum age for a member to be considered a mature person, and thus receive administrative privileges on the platform.
			 */
			ageOfAMatureMemberMessage: string
			/**
			 * years
			 */
			years: string
		}
		newAccountSection: {
			/**
			 * New account
			 */
			menu: string
			/**
			 * New account
			 */
			title: string
			/**
			 * Configure everything related to creating new member and guest accounts.
			 */
			message: string
			/**
			 * How are new user accounts created?
			 */
			howAreNewUserAccountsCreated: string
			/**
			 * By member invitation only
			 */
			byMemberInvitationOnly: string
			/**
			 * Public registration page
			 */
			publicRegistrationPage: string
			/**
			 * New registrations disabled
			 */
			newRegistrationsDisabled: string
			/**
			 * Who can send invitations to new member accounts?
			 */
			whoCanSendInvitationsToNewMemberAccounts: string
			/**
			 * Admin members, of mature age
			 */
			adminMembersOfMatureAge: string
			/**
			 * Admin members
			 */
			adminMembers: string
			/**
			 * Who can send invitations to new guest accounts?
			 */
			whoCanSendInvitationsToNewGuestAccounts: string
		}
		guestsSection: {
			/**
			 * Guests
			 */
			menu: string
			/**
			 * Guests
			 */
			title: string
			/**
			 * Manage guest user account privileges here.
			 */
			message: string
			/**
			 * Features enabled for guest accounts
			 */
			featuresEnabled: string
			/**
			 * Feedback submission
			 */
			feedbackSubmission: string
			/**
			 * Polls with guest-enabled content
			 */
			pollsWithGuestEnabledContent: string
			/**
			 * Topics with guest-enabled content
			 */
			topicsWithGuestEnabledContent: string
			/**
			 * News with guest-enabled content
			 */
			newsWithGuestEnabledContent: string
		}
		feedbackSection: {
			/**
			 * Feedback
			 */
			menu: string
			/**
			 * Feedback
			 */
			title: string
			message: string
		}
		pollsSection: {
			/**
			 * Polls
			 */
			menu: string
			/**
			 * Polls
			 */
			title: string
			/**
			 * Configure everything related to platform polls.
			 */
			message: string
			/**
			 * Maximum number of polls per month
			 */
			maximumNumberOfPolls: string
			/**
			 * Set the maximum number of polls that can be created per month on the platform. The amount must be the total value of each user's polls added together.
			 */
			maximumNumberOfPollsMessage: string
		}
		topicsSection: {
			/**
			 * Topics
			 */
			menu: string
			/**
			 * Topics
			 */
			title: string
			/**
			 * Configure everything related to the platform topics.
			 */
			message: string
			/**
			 * Chat rooms on topics
			 */
			chatRoomsOnTopics: string
			/**
			 * Configure whether within each topic there will be a chat room related to the subject of the same topic.
			 */
			chatRoomsOnTopicsMessage: string
			/**
			 * Enable chat room within topics
			 */
			enableChatRoomWithinTopics: string
			/**
			 * Disable chatroom on topics
			 */
			disableChatroomOnTopics: string
		}
		newsReaderSection: {
			/**
			 * Newspaper
			 */
			menu: string
			/**
			 * Group newspaper
			 */
			title: string
			message: string
			/**
			 * Newspaper name
			 */
			newspaperName: string
			/**
			 * Newspaper link
			 */
			newspaperLink: string
			/**
			 * Periodicity of the newspaper edition
			 */
			periodicityOfTheNewspaper: string
			/**
			 * Configure how many days it takes for a new edition to be published.
			 */
			periodicityOfTheNewspaperMessage: string
			/**
			 * days
			 */
			days: string
		}
	}
	polls: {
		exampleOne: {
			/**
			 * What will be the name of Jane and Joe's baby?
			 */
			title: string
			/**
			 * In this poll you can suggest the name of my son and John. If the name you suggested is chosen, in addition to the honor of that choice, you will also receive an <b>amazing surprise gift</b>! 🎉
			 */
			message: string
		}
		exampleTwo: {
			/**
			 * Will Jane and Joe's baby be a boy or a girl?
			 */
			title: string
			/**
			 * I created this poll for you to try to guess if my and John's child will be a boy or a girl. Everyone who answered correctly received a gift.
			 */
			message: string
		}
		/**
		 * Polls
		 */
		polls: string
		/**
		 * Poll management
		 */
		pollManagement: string
		/**
		 * In this section you can answer other users' polls, create your own polls and access the results.
		 */
		pollManagementMessage: string
		/**
		 * Create poll
		 */
		createPoll: string
		/**
		 * View all polls
		 */
		viewAllPolls: string
		/**
		 * View only active polls
		 */
		viewOnlyActivePolls: string
		/**
		 * All polls
		 */
		allPolls: string
		/**
		 * Active polls
		 */
		activePolls: string
		/**
		 * ✔ Answered
		 */
		answered: string
		/**
		 * ✔ Unanswered
		 */
		unanswered: string
		/**
		 * Name suggestion
		 */
		nameSuggestion: string
		/**
		 * Name meaning
		 */
		nameMeaning: string
		/**
		 * Name gender
		 */
		nameGender: string
		/**
		 * Male
		 */
		male: string
		/**
		 * Feminine
		 */
		feminine: string
		/**
		 * Unisex
		 */
		unisex: string
		/**
		 * Answer poll
		 */
		answerPoll: string
		/**
		 * Poll answered 🎉
		 */
		pollAnswered: string
		/**
		 * Within a week all answers will be published
		 */
		pollAnsweredMessage: string
		/**
		 * What do you want to do now?
		 */
		whatDoYouWantToDoNow: string
		/**
		 * Go to polls
		 */
		goToPolls: string
		/**
		 * Go to home page
		 */
		goToHomePage: string
		/**
		 * ANSWERS
		 */
		answers: string
		/**
		 * Girl
		 */
		girl: string
		/**
		 * Boy
		 */
		boy: string
		/**
		 * People who responded
		 */
		peopleWhoResponded: string
		/**
		 * Poll title
		 */
		pollTitle: string
		/**
		 * Question
		 */
		question: string
		/**
		 * Poll created
		 */
		pollCreated: string
		/**
		 * Your poll was created successfully
		 */
		pollCreatedMessage: string
		/**
		 * Poll closed
		 */
		pollClosed: string
	}
	profiles: {
		/**
		 * Profiles
		 */
		profiles: string
		/**
		 * User profile
		 */
		userProfile: string
		/**
		 * Users
		 */
		users: string
		/**
		 * Platform users
		 */
		platformUsers: string
		warning: {
			/**
			 * There is only one example of a user profile on the platform, the following:
			 */
			onlyOneExemple: string
			/**
			 * Would you like to open this example?
			 */
			wouldYouLikeToOpenThisExample: string
			/**
			 * Open the example
			 */
			openTheExample: string
			/**
			 * Do not open
			 */
			doNotOpen: string
		}
		/**
		 * Name
		 */
		name: string
		/**
		 * Full name
		 */
		fullName: string
		/**
		 * Short name
		 */
		shortName: string
		/**
		 * Nickname
		 */
		nickname: string
		/**
		 * Account
		 */
		account: string
		/**
		 * Birth date
		 */
		birthDate: string
		/**
		 * Age
		 */
		age: string
		/**
		 * years
		 */
		years: string
		/**
		 * Useful links
		 */
		usefulLinks: string
		/**
		 * Edit this profile data
		 */
		editUserData: string
		/**
		 * See other users profiles
		 */
		goToOtherProfiles: string
		/**
		 * Learn more about account types
		 */
		goToAccountTypes: string
	}
	signIn: {
		/**
		 * Sign in
		 */
		signIn: string
		/**
		 * Nickname or email
		 */
		nicknameOrEmail: string
		/**
		 * Nickname
		 */
		nickname: string
		/**
		 * Email
		 */
		email: string
		/**
		 * Password
		 */
		password: string
		/**
		 * If you are not a user,
		 */
		invitationPart1: string
		/**
		 * request an invitation
		 */
		invitationPart2: string
	}
	signUp: {
		requirements: {
			/**
			 * Requirements
			 */
			requirements: string
			/**
			 * Sign up requirements
			 */
			signUpRequirements: string
			/**
			 * About
			 */
			about: string
			/**
			 * Pending
			 */
			pending: string
			/**
			 * Completed
			 */
			completed: string
			/**
			 * Almost done!
			 */
			almostDone: string
			/**
			 * Your account is currently in <b>pre-registration</b> status. It is still necessary to complete some prerequisites for you to be able to access the platform. Click on the <b>Pending</b> tab to view your open tasks.
			 */
			aboutMessage: string
			/**
			 * Pending tasks
			 */
			pendingTasks: string
			/**
			 * You have <b>1</b> pending task.
			 */
			pendingTaskWarning: string
			pendingTasksItem: {
				/**
				 * User data confirmation
				 */
				userDataConfirmation: string
			}
			/**
			 * Task history
			 */
			taskHistory: string
			/**
			 * today
			 */
			today: string
			completedTaskItem: {
				/**
				 * Default language changed.
				 */
				defaultLanguageChanged: string
				/**
				 * Profile image uploaded.
				 */
				profileImageUploaded: string
				/**
				 * Chosen interface visual theme.
				 */
				chosenInterfaceVisualTheme: string
				/**
				 * Email <b>johndoe@gmail.com</b> has been confirmed.
				 */
				emailConfirmed: string
				/**
				 * Defined the nickname: <b>@john</b>
				 */
				nicknameDefined: string
				/**
				 * Access password changed.
				 */
				passwordChanged: string
				/**
				 * Member invitation has been approved.
				 */
				memberInvitationApproved: string
				/**
				 * You have requested an invitation to be a platform member.
				 */
				memberInvitationRequested: string
			}
			dataConfirmation: {
				/**
				 * Data confirmation
				 */
				dataConfirmation: string
				/**
				 * Review your data
				 */
				reviewYourData: string
				/**
				 * Below are the data filled in during your user pre-registration, so you can review them.
				 */
				dataConfirmationSectionMessage: string
				fields: {
					/**
					 * Name
					 */
					name: string
					/**
					 * Email
					 */
					email: string
					/**
					 * Nickname
					 */
					nickname: string
					/**
					 * Theme
					 */
					theme: string
					/**
					 * Language
					 */
					language: string
					/**
					 * Profile image
					 */
					profileImage: string
				}
				/**
				 * Click <b>Confirm data</b> if all the data above is correct.
				 */
				confirmDataMessage: string
				/**
				 * Confirm data
				 */
				confirmData: string
			}
		}
		welcome: {
			/**
			 * Welcome!
			 */
			welcome: string
			/**
			 * You are the newest member of the platform.
			 */
			youAreTheNewestMember: string
			/**
			 * Your registration has been successfully completed and you are now the newest member of the platform. Click the button below to be redirected to the home page.
			 */
			welcomeMessage: string
			/**
			 * Go to the home page
			 */
			goToTheHomePage: string
		}
	}
	topics: {
		exampleOne: {
			/**
			 * Visual identity of the Doe Family
			 */
			title: string
		}
		exampleTwo: {
			/**
			 * Create your own digital news panel
			 */
			title: string
		}
		exampleThree: {
			/**
			 * About the Doe Family website
			 */
			title: string
		}
		/**
		 * Topics
		 */
		topics: string
		/**
		 * Platform member topics
		 */
		groupTopics: string
		/**
		 * In this platform section you can create and manage "topics". And a “topic” consists of a group of pages with shared editing, with all pages related to the same central subject.
		 */
		groupTopicsMessage: string
		/**
		 * Existing topics
		 */
		existingTopics: string
		example: {
			/**
			 * Intro
			 */
			intro: string
			/**
			 * Visual identity of the Doe Family
			 */
			topicTitle: string
			/**
			 * Page
			 */
			page: string
			/**
			 * In this topic everything is related to the visual identity of the Doe Family. For example: the history of the family coat of arms; downloadable images and files; etc.
			 */
			introMessage: string
			/**
			 * This is an example of a topic created by a member of the platform. A "topic" consists of a set of pages related to a central theme.
			 */
			warningMessage: string
			/**
			 * Coat of arms
			 */
			coatOfArms: string
			/**
			 * Doe Family coat of arms
			 */
			doeFamilyCoatOfArms: string
			/**
			 * Traditional coat of arms
			 */
			traditionalCoatOfArms: string
			/**
			 * This is a reinterpretation of the old Doe Family coat of arms. This coat of arms is versatile and can be used in almost any context.
			 */
			traditionalCoatOfArmsMessage: string
			/**
			 * Fun coat of arms
			 */
			funCoatOfArms: string
			/**
			 * This is a lively colored coat of arms and was created to be used in fun contexts such as parties and recreational events.
			 */
			funCoatOfArmsMessage: string
			/**
			 * Mourning coat of arms
			 */
			mourningCoatOfArms: string
			/**
			 * This is a coat of arms with sober colors to be used in mourning circumstances.
			 */
			mourningCoatOfArmsMessage: string
			/**
			 * This is another example of a page created within the topic by one of the platform's members. Because any member can create pages within the topics created by other members.
			 */
			anotherPageMessage: string
			/**
			 * today at 3 am
			 */
			chatMessageDate: string
			/**
			 * Example of message sent
			 */
			chatMessage: string
			/**
			 * Place to write messages
			 */
			placeToWriteMessages: string
		}
		warningMessage: {
			/**
			 * This is an incomplete example. Other subpages and functionality will be implemented.
			 */
			incompleteExample: string
			/**
			 * There is only one topic example on the platform, the following:
			 */
			onlyOneExample: string
			/**
			 * Would you like to open this example?
			 */
			wouldYouLikeToOpenThisExample: string
			/**
			 * Open the example
			 */
			openTheExample: string
			/**
			 * Do not open
			 */
			doNotOpen: string
		}
		/**
		 * back
		 */
		back: string
	}
	userSettings: {
		/**
		 * Settings
		 */
		userSettings: string
		menu: {
			/**
			 * General
			 */
			general: string
			/**
			 * Profile image
			 */
			profileImage: string
			/**
			 * Theme
			 */
			theme: string
		}
		/**
		 * Account settings
		 */
		generalSettings: string
		/**
		 * Configure your user profile data here.
		 */
		generalSettingsMessage: string
		/**
		 * Profile image
		 */
		profileImage: string
		/**
		 * Upload an image to your user profile.
		 */
		profileImageMessage: string
		/**
		 * Theme
		 */
		theme: string
		/**
		 * Full name
		 */
		fullName: string
		/**
		 * Email
		 */
		email: string
		/**
		 * Password
		 */
		password: string
		/**
		 * Birth date
		 */
		birthDate: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Click here to upload
		 */
		clickHereToUpload: () => LocalizedString
		/**
		 * User
		 */
		user: () => LocalizedString
		/**
		 * Users
		 */
		users: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * First name
		 */
		firstName: () => LocalizedString
		/**
		 * Full name
		 */
		fullName: () => LocalizedString
		/**
		 * Middle name
		 */
		middleName: () => LocalizedString
		/**
		 * Middle names
		 */
		middleNames: () => LocalizedString
		/**
		 * Nickname
		 */
		nickname: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * History
		 */
		history: () => LocalizedString
		/**
		 * Section name
		 */
		sectionName: () => LocalizedString
		/**
		 * Home page
		 */
		homePage: () => LocalizedString
		/**
		 * Useful links
		 */
		usefulLinks: () => LocalizedString
		/**
		 * Top
		 */
		top: () => LocalizedString
		/**
		 * Non responsive
		 */
		nonResponsive: () => LocalizedString
		/**
		 * It's not mobile friendly
		 */
		nonResponsive2: () => LocalizedString
		/**
		 * You are opening a link to an external website
		 */
		openingExternalWebsite: () => LocalizedString
		/**
		 * Open the website
		 */
		openTheWebsite: () => LocalizedString
		/**
		 * Do not open
		 */
		doNotOpen: () => LocalizedString
		/**
		 * This site, for now, is just a layout example.
		 */
		warningMessage: () => LocalizedString
		/**
		 * Note: The site is just a layout example, it is not possible to change the data.
		 */
		warningMessage2: () => LocalizedString
		/**
		 * This site, for now, is just an example of a layout under development. No form content will be saved and many functional and visual changes will still be made.
		 */
		warningMessage3: () => LocalizedString
		/**
		 * This site, for now, is just an example of a layout in the development stage. Many functional and visual changes are yet to be made.
		 */
		warningMessage4: () => LocalizedString
		/**
		 * The final version of this page will be TOTALLY different from this example.
		 */
		warningMessage5: () => LocalizedString
	}
	language: {
		/**
		 * Language
		 */
		language: () => LocalizedString
		/**
		 * Languages
		 */
		languages: () => LocalizedString
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * Portuguese
		 */
		pt: () => LocalizedString
		originalName: {
			/**
			 * English
			 */
			en: () => LocalizedString
			/**
			 * Português
			 */
			pt: () => LocalizedString
		}
		/**
		 * Language settings
		 */
		languageSettings: () => LocalizedString
		/**
		 * Choose a language
		 */
		chooseALanguage: () => LocalizedString
		/**
		 * Below are the translation options provided by the platform. Choose your preferred language.
		 */
		messageToChooseLanguage: () => LocalizedString
		/**
		 * Confirm language choice
		 */
		confirmLanguageChoice: () => LocalizedString
	}
	theme: {
		/**
		 * Theme
		 */
		theme: () => LocalizedString
		/**
		 * Themes
		 */
		themes: () => LocalizedString
		themeName: {
			/**
			 * Default
			 */
			'default': () => LocalizedString
			/**
			 * Potato
			 */
			'light-potato': () => LocalizedString
			/**
			 * Reptilian
			 */
			'light-reptilian': () => LocalizedString
		}
		themeMessage: {
			/**
			 * The most beautiful theme in the galaxy
			 */
			'default': () => LocalizedString
			/**
			 * This theme is delicious
			 */
			'light-potato': () => LocalizedString
			/**
			 * A theme from another planet
			 */
			'light-reptilian': () => LocalizedString
		}
		/**
		 * Theme settings
		 */
		themeSettings: () => LocalizedString
		/**
		 * Theme in use
		 */
		themeInUse: () => LocalizedString
		/**
		 * Current
		 */
		current: () => LocalizedString
		/**
		 * Themes available
		 */
		themesAvailable: () => LocalizedString
	}
	menu: {
		/**
		 * Menu
		 */
		menu: () => LocalizedString
		/**
		 * Platform settings
		 */
		adminSettings: () => LocalizedString
		/**
		 * Feedback
		 */
		feedback: () => LocalizedString
		/**
		 * History
		 */
		activitiesHistory: () => LocalizedString
		/**
		 * All users
		 */
		platformUsers: () => LocalizedString
		/**
		 * Topics
		 */
		topics: () => LocalizedString
		/**
		 * Invitations
		 */
		invitations: () => LocalizedString
		/**
		 * User settings
		 */
		userSettings: () => LocalizedString
		/**
		 * Polls
		 */
		polls: () => LocalizedString
		/**
		 * Memorandum
		 */
		memorandum: () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * News
		 */
		news: () => LocalizedString
	}
	accounts: {
		/**
		 * Account
		 */
		account: () => LocalizedString
		/**
		 * Accounts
		 */
		accounts: () => LocalizedString
		/**
		 * Privileges
		 */
		privileges: () => LocalizedString
		/**
		 * Account types
		 */
		accountTypes: () => LocalizedString
		/**
		 * About platform accounts
		 */
		aboutPlatformAccounts: () => LocalizedString
		/**
		 * Platform account types
		 */
		platformAccountTypes: () => LocalizedString
		/**
		 * Users can have different types of accounts. These types of accounts exist to facilitate access and management of the platform. The existing account types are as follows:
		 */
		platformAccountTypesMessage: () => LocalizedString
		/**
		 * Extra privileges for full members
		 */
		extraPrivilegesForFullMembers: () => LocalizedString
		/**
		 * All "<b>Full Member</b>" accounts can gain some extra privileges attached to them, the following privileges:
		 */
		extraPrivilegesForFullMembersMessage: () => LocalizedString
		accountType: {
			/**
			 * Admin
			 */
			admin: () => LocalizedString
			/**
			 * Maintainer
			 */
			maintainer: () => LocalizedString
			/**
			 * Developer
			 */
			developer: () => LocalizedString
			/**
			 * Full member
			 */
			fullMember: () => LocalizedString
			/**
			 * Partner member
			 */
			partnerMember: () => LocalizedString
			/**
			 * Guest
			 */
			guest: () => LocalizedString
		}
		accountDescription: {
			/**
			 * This is the most privileged type of account, aimed at lifetime members.
			 */
			fullMember: () => LocalizedString
			/**
			 * This is an account type aimed at users who have some kind of relationship with a full member.
			 */
			partnerMember: () => LocalizedString
			/**
			 * Account aimed at a guest user who knows someone on the platform.
			 */
			guest: () => LocalizedString
		}
		privilegeType: {
			/**
			 * Administrator
			 */
			administrator: () => LocalizedString
			/**
			 * Mature age
			 */
			matureAge: () => LocalizedString
			/**
			 * Developer
			 */
			developer: () => LocalizedString
		}
		privilegeDescription: {
			/**
			 * This is a privilege that allows a user to change platform settings.
			 */
			administrator: () => LocalizedString
			/**
			 * Member old enough to be considered a mature user to handle choices that require more responsibility.
			 */
			matureAge: () => LocalizedString
			/**
			 * Members who have fulfilled the necessary prerequisites to change the platform code.
			 */
			developer: () => LocalizedString
		}
		/**
		 * Full member account
		 */
		fullMemberAccount: () => LocalizedString
		/**
		 * Your account type
		 */
		yourAccountType: () => LocalizedString
		/**
		 * You have an account of the type
		 */
		youHaveAnAccountOfTheType: () => LocalizedString
	}
	activities: {
		/**
		 * Activity
		 */
		activity: () => LocalizedString
		/**
		 * Activities
		 */
		activities: () => LocalizedString
		/**
		 * Activity history
		 */
		activityHistory: () => LocalizedString
		/**
		 * Latest activities on the platform
		 */
		latestActivitiesOnThePlatform: () => LocalizedString
		activityName: {
			/**
			 * Created feedback
			 */
			createdFeedback: () => LocalizedString
			/**
			 * Created memorandum
			 */
			createdMemo: () => LocalizedString
			/**
			 * Created news
			 */
			createdNews: () => LocalizedString
			/**
			 * Created poll
			 */
			createdPoll: () => LocalizedString
		}
	}
	feedback: {
		exampleOne: {
			/**
			 * A pink button could be created
			 */
			title: () => LocalizedString
			/**
			 * I find the color of the platform buttons very ugly, so I suggest a color change. I think there should be a possibility for users to choose the color of their buttons in the settings. I would love to be able to click pink buttons.
			 */
			message: () => LocalizedString
			/**
			 * This idea is cool. Will any developer be able to solve this issue?
			 */
			answerOne: () => LocalizedString
			/**
			 * I really liked this idea too. I'll try to implement the code for this pink button, but it seems too complicated, I don't know if I'll be able to.
			 */
			answerTwo: () => LocalizedString
		}
		exampleTwo: {
			/**
			 * New functionality to register family tree?
			 */
			title: () => LocalizedString
			message: () => LocalizedString
		}
		exampleThree: {
			/**
			 * Spelling error on the home page
			 */
			title: () => LocalizedString
			message: () => LocalizedString
		}
		exampleFour: {
			/**
			 * Can we create our version of Netflix?
			 */
			title: () => LocalizedString
			message: () => LocalizedString
		}
		/**
		 * Feedback
		 */
		feedback: () => LocalizedString
		/**
		 * Would you like to share your opinion? Any suggestions for the platform? If yes,
		 */
		description: () => LocalizedString
		/**
		 * post your comment here
		 */
		postYourCommentHere: () => LocalizedString
		/**
		 * Create feedback
		 */
		createFeedback: () => LocalizedString
		/**
		 * Manage feedback
		 */
		manageFeedback: () => LocalizedString
		/**
		 * Create feedback about the platform
		 */
		createFeedbackAboutThePlatform: () => LocalizedString
		/**
		 * Create feedback about the platform to send to the members. This feedback can be feature suggestions, reports of malfunctions, and opinions.
		 */
		createFeedbackAboutThePlatformMessage: () => LocalizedString
		/**
		 * Title of your feedback
		 */
		titleOfYourFeedback: () => LocalizedString
		/**
		 * Messages
		 */
		messages: () => LocalizedString
		/**
		 * Write message
		 */
		writeMessage: () => LocalizedString
		/**
		 * Answer
		 */
		answer: () => LocalizedString
		/**
		 * Message
		 */
		message: () => LocalizedString
		/**
		 * Please write your message below, and if possible, include a large amount of data and details in your content, so that we can handle and understand the information in the best possible way.
		 */
		messageMessage: () => LocalizedString
		/**
		 * Send feedback
		 */
		sendFeedback: () => LocalizedString
		/**
		 * Feedback management
		 */
		feedbackManagement: () => LocalizedString
		/**
		 * Author
		 */
		author: () => LocalizedString
		/**
		 * By
		 */
		by: () => LocalizedString
		/**
		 * Last interaction
		 */
		lastInteraction: () => LocalizedString
		/**
		 * Publication date
		 */
		publicationDate: () => LocalizedString
		/**
		 * There is only one example of feedback on the platform, the following:
		 */
		justOneExample: () => LocalizedString
		/**
		 * Would you like to open this example?
		 */
		wouldYouLikeToOpenThisExample: () => LocalizedString
		/**
		 * Open the example
		 */
		openTheExample: () => LocalizedString
		/**
		 * Do not open
		 */
		doNotOpenTheExample: () => LocalizedString
		/**
		 * Feedback created ✌
		 */
		feedbackCreated: () => LocalizedString
		/**
		 * Your feedback has been sent to platform members
		 */
		feedbackCreatedMessage: () => LocalizedString
		/**
		 * What would you like to do now?
		 */
		whatWouldYouLikeToDoNow: () => LocalizedString
		/**
		 * Create new feedback
		 */
		createNewFeedback: () => LocalizedString
		/**
		 * Go to home page
		 */
		goToHomePage: () => LocalizedString
	}
	forms: {
		userTypesWithAccess: {
			/**
			 * Account types that can access content
			 */
			title: () => LocalizedString
			/**
			 * "{mainAccountType}" accounts can view all content on the platform, however, for other types of accounts it is necessary to grant access. Select below which accounts you want to grant access to the content:
			 */
			message: (arg: { mainAccountType: string }) => LocalizedString
		}
	}
	homePage: {
		headerMessageExample: {
			/**
			 * What will the child be called?
			 */
			title: () => LocalizedString
			/**
			 * I have just published a poll on the platform, where you can suggest the name of John's and mine's son. If the name you suggested is chosen, in addition to the honor of this choice, you will also win a <b>super gift</b>! 🎉
			 */
			description: () => LocalizedString
			/**
			 * Jane Doe - @jane
			 */
			author: () => LocalizedString
		}
		sections: {
			/**
			 * Platform sections
			 */
			title: () => LocalizedString
			/**
			 * User settings
			 */
			userSettings: () => LocalizedString
			/**
			 * Polls and answers
			 */
			polls: () => LocalizedString
			/**
			 * Group topics
			 */
			topics: () => LocalizedString
			/**
			 * All users
			 */
			users: () => LocalizedString
			/**
			 * Group newspaper
			 */
			newsReader: () => LocalizedString
			/**
			 * Invitations management
			 */
			invitations: () => LocalizedString
			/**
			 * Feedback management
			 */
			feedback: () => LocalizedString
			/**
			 * Platform settings
			 */
			platformSettings: () => LocalizedString
			/**
			 * Activities history
			 */
			activitiesHistory: () => LocalizedString
			/**
			 * Memorandum
			 */
			memorandum: () => LocalizedString
		}
		polls: {
			/**
			 * Published polls
			 */
			title: () => LocalizedString
		}
		memos: {
			/**
			 * Memorandum
			 */
			title: () => LocalizedString
		}
		lastNews: {
			/**
			 * Last news - {newsReaderName}
			 */
			title: (arg: { newsReaderName: string }) => LocalizedString
		}
		topics: {
			/**
			 * Group topics
			 */
			title: () => LocalizedString
		}
	}
	invitations: {
		/**
		 * Invitations
		 */
		invitations: () => LocalizedString
		request: {
			/**
			 * Invitation request
			 */
			invitationRequest: () => LocalizedString
			/**
			 * Request an invitation so you can register on the platform.
			 */
			invitationMessage: () => LocalizedString
			/**
			 * Name
			 */
			name: () => LocalizedString
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * Message
			 */
			message: () => LocalizedString
			/**
			 * Return
			 */
			'return': () => LocalizedString
			/**
			 * Request invitation
			 */
			requestInvitation: () => LocalizedString
			/**
			 * Congratulations!
			 */
			congratulations: () => LocalizedString
			/**
			 * Your invitation has been approved
			 */
			invitationApproved: () => LocalizedString
			/**
			 * The invitation for you to become a member of the platform has been approved. Now <b>the next step is to resolve the pending issues</b> of your registration. Click on the button below to view your pending issues.
			 */
			pendingIssuesMessage: () => LocalizedString
			/**
			 * Go to registration issues
			 */
			goToRegistrationIssues: () => LocalizedString
		}
		requestsReceived: {
			/**
			 * Requests
			 */
			requests: () => LocalizedString
			/**
			 * Recent invite requests
			 */
			recentInviteRequests: () => LocalizedString
			/**
			 * Pending invite requests
			 */
			pendingInviteRequests: () => LocalizedString
			/**
			 * Approved invite requests
			 */
			approvedInviteRequests: () => LocalizedString
			/**
			 * Rejected invite requests
			 */
			rejectedInviteRequests: () => LocalizedString
			/**
			 * Request date
			 */
			requestDate: () => LocalizedString
			/**
			 * Approval date
			 */
			approvalDate: () => LocalizedString
			/**
			 * Rejection date
			 */
			rejectionDate: () => LocalizedString
			/**
			 * Name
			 */
			name: () => LocalizedString
			/**
			 * Request message
			 */
			requestMessage: () => LocalizedString
			/**
			 * Approved by
			 */
			approvedBy: () => LocalizedString
			/**
			 * Rejected by
			 */
			rejectedBy: () => LocalizedString
			/**
			 * Account type given
			 */
			accountTypeGiven: () => LocalizedString
			/**
			 * Justification
			 */
			justification: () => LocalizedString
			examples: {
				/**
				 * Hi family! Please accept my request.
				 */
				pendingMessageOne: () => LocalizedString
				/**
				 * I'm Jane's friend, and I would like a "guest account" so that I can answer my friend's polls. Thanks! :)
				 */
				pendingMessageTwo: () => LocalizedString
				/**
				 * Hey guys! Accept my request.
				 */
				approvedMessageOne: () => LocalizedString
				/**
				 * I don't like this guy
				 */
				rejectedJustificationOne: () => LocalizedString
				/**
				 * Hey! I would like to be part of your group.
				 */
				rejectedMessageOne: () => LocalizedString
			}
		}
		sendInvitation: {
			/**
			 * Send invitation
			 */
			sendInvitation: () => LocalizedString
			/**
			 * Name of person to be invited
			 */
			nameOfPersonToBeInvited: () => LocalizedString
			/**
			 * Email of person to be invited
			 */
			emailOfPersonToBeInvited: () => LocalizedString
			/**
			 * Message
			 */
			message: () => LocalizedString
			/**
			 * Invitation sent ✌
			 */
			invitationSent: () => LocalizedString
			/**
			 * Your invitation has been sent successfully
			 */
			invitationSentMessage: () => LocalizedString
			/**
			 * What would you like to do now?
			 */
			whatWouldYouLikeToDoNow: () => LocalizedString
			/**
			 * Go to invitation management
			 */
			goToInvitationManagement: () => LocalizedString
			/**
			 * Go to home page
			 */
			goToHomePage: () => LocalizedString
		}
		invitationsSent: {
			/**
			 * Invitations sent
			 */
			invitationsSent: () => LocalizedString
			/**
			 * Recently sent invitations
			 */
			recentlySentInvitations: () => LocalizedString
			/**
			 * Sent date
			 */
			sentDate: () => LocalizedString
			/**
			 * Sent by
			 */
			sentBy: () => LocalizedString
			/**
			 * Sent to
			 */
			sentTo: () => LocalizedString
			/**
			 * Message
			 */
			message: () => LocalizedString
			example: {
				/**
				 * Hey friend! Come be part of my family's platform.
				 */
				message: () => LocalizedString
			}
		}
	}
	memos: {
		/**
		 * Memorandum
		 */
		memos: () => LocalizedString
		/**
		 * Memorandum
		 */
		memorandum: () => LocalizedString
		exampleOne: {
			/**
			 * 18.jun.2022
			 */
			date: () => LocalizedString
			/**
			 * Jane's trip scheduled
			 */
			title: () => LocalizedString
			/**
			 * Published on June 18, 2022.
			 */
			publishedOn: () => LocalizedString
			/**
			 * Dear Family
			 */
			dearFamily: () => LocalizedString
			/**
			 * I just bought my plane ticket to Brazil. I will arrive at the airport in Porto Alegre/RS, on the 23rd of July, at 10 am.
			 */
			paragraphOne: () => LocalizedString
			/**
			 * And the next day, the 24th, I would like to meet with the whole family at grandma Eliza Doe's house. So book a space in your calendar.
			 */
			paragraphTwo: () => LocalizedString
			/**
			 * With love
			 */
			kindRegards: () => LocalizedString
			/**
			 * Note: I'm taking some sweets and gifts that I'm going to give to everyone who comes to see me at grandma Eliza's house.
			 */
			note: () => LocalizedString
		}
		exampleTwo: {
			/**
			 * 02.jun.2022
			 */
			date: () => LocalizedString
			/**
			 * Next Doe Family reunion
			 */
			title: () => LocalizedString
		}
		/**
		 * Go to memos
		 */
		goToMemos: () => LocalizedString
		/**
		 * Go to home page
		 */
		goToHomePage: () => LocalizedString
		warningMessage: {
			/**
			 * There is only one memorandum example on the platform, the following:
			 */
			onlyOneExample: () => LocalizedString
			/**
			 * Would you like to open this example?
			 */
			wouldYouLikeToOpenThisExample: () => LocalizedString
			/**
			 * Open the example
			 */
			openTheExample: () => LocalizedString
			/**
			 * Do not open
			 */
			doNotOpen: () => LocalizedString
		}
		/**
		 * Memos management
		 */
		memoManagement: () => LocalizedString
		/**
		 * A memo is a practical communication and record, in text format, on some relevant subject. Here in this section it is possible to create memos to send to all members of the platform, and also, it is possible to read memos previously sent.
		 */
		memoManagementMessage: () => LocalizedString
		/**
		 * Create memo
		 */
		createMemo: () => LocalizedString
		/**
		 * Show all memos
		 */
		showAllMemos: () => LocalizedString
		/**
		 * Show recent memos only
		 */
		showRecentMemos: () => LocalizedString
		/**
		 * All memos
		 */
		allMemos: () => LocalizedString
		/**
		 * Recent memos
		 */
		recentMemos: () => LocalizedString
		/**
		 * Memo created 🎉
		 */
		memoCreated: () => LocalizedString
		/**
		 * Your memo has been created and sent to members
		 */
		memoCreatedMessage: () => LocalizedString
		/**
		 * What do you want to do now?
		 */
		whatDoYouWantToDoNow: () => LocalizedString
		/**
		 * Title
		 */
		title: () => LocalizedString
		/**
		 * Message
		 */
		message: () => LocalizedString
		/**
		 * Create and send memo
		 */
		createAndSendMemo: () => LocalizedString
	}
	news: {
		exampleOne: {
			/**
			 * What will the child be called?
			 */
			title: () => LocalizedString
		}
		exampleTwo: {
			/**
			 * Alicia has a new crush! 😱
			 */
			title: () => LocalizedString
		}
		exampleThree: {
			/**
			 * David wins swimming gold medal
			 */
			title: () => LocalizedString
		}
		/**
		 * News
		 */
		news: () => LocalizedString
		/**
		 * There is only one example of news on the platform, the following:
		 */
		thereIsOnlyOneExample: () => LocalizedString
		/**
		 * Would you like to open this example?
		 */
		wouldYouLikeToOpen: () => LocalizedString
		/**
		 * Where would you like to open this news?
		 */
		whereOpenNewsMessage: () => LocalizedString
		/**
		 * Open on this platform
		 */
		openOnThisPlatform: () => LocalizedString
		/**
		 * On this platform
		 */
		onThisPlatform: () => LocalizedString
		/**
		 * Do not open
		 */
		doNotOpen: () => LocalizedString
		/**
		 * News data
		 */
		newsData: () => LocalizedString
		/**
		 * Posted on
		 */
		postedOn: () => LocalizedString
		/**
		 * Last updated
		 */
		lastUpdated: () => LocalizedString
		/**
		 * Go to
		 */
		goTo: () => LocalizedString
		/**
		 * Go to news section
		 */
		goToNewsSection: () => LocalizedString
		/**
		 * Go to home page
		 */
		goToHomePage: () => LocalizedString
		/**
		 * Suggest changes to the news
		 */
		suggestChangesToTheNews: () => LocalizedString
		/**
		 * Read this news at
		 */
		readThisNewsAt: () => LocalizedString
		/**
		 * Author
		 */
		author: () => LocalizedString
		/**
		 * What would you like to do now
		 */
		whatWouldYouLikeToDoNow: () => LocalizedString
		suggestChange: {
			/**
			 * Suggest news change
			 */
			suggestNewsChange: () => LocalizedString
			/**
			 * Target news
			 */
			targetNews: () => LocalizedString
			/**
			 * Title
			 */
			title: () => LocalizedString
			/**
			 * Please describe your proposed amendment in detail below.
			 */
			describeMessage: () => LocalizedString
			/**
			 * Send suggestion
			 */
			sendSuggestion: () => LocalizedString
			/**
			 * Suggestion sent
			 */
			suggestionSent: () => LocalizedString
			/**
			 * Your suggestion has been sent to the author of the news.
			 */
			suggestionSentMessage: () => LocalizedString
			/**
			 * Back to previous news
			 */
			backToPreviousNews: () => LocalizedString
		}
		/**
		 * Posted
		 */
		posted: () => LocalizedString
		/**
		 * New/drafts
		 */
		newAndDrafts: () => LocalizedString
		/**
		 * Scheduled
		 */
		scheduled: () => LocalizedString
		/**
		 * News from
		 */
		newsFrom: () => LocalizedString
		/**
		 * Next edition
		 */
		nextEdition: () => LocalizedString
		/**
		 * <b>July 5</b>, 2022
		 */
		nextEditionDate: () => LocalizedString
		/**
		 * Periodicity
		 */
		periodicity: () => LocalizedString
		/**
		 * Every 40 days
		 */
		periodicityValue: () => LocalizedString
		/**
		 * You have <b>no</b> news scheduled
		 */
		noNewsScheduled: () => LocalizedString
		/**
		 * Edition
		 */
		edition: () => LocalizedString
		/**
		 * Create news/draft
		 */
		createNewDraft: () => LocalizedString
		/**
		 * Drafts
		 */
		drafts: () => LocalizedString
		/**
		 * You have no drafts
		 */
		noDrafts: () => LocalizedString
		/**
		 * Scheduled news
		 */
		scheduledNews: () => LocalizedString
		/**
		 * You have no news scheduled for the next edition of
		 */
		noNewsScheduledMessage: () => LocalizedString
		/**
		 * To create a new news go to the tab
		 */
		toCreateANewNewsGoToTheTab: () => LocalizedString
		createNews: {
			/**
			 * News creation
			 */
			newsCreation: () => LocalizedString
			/**
			 * Title
			 */
			title: () => LocalizedString
			/**
			 * Image
			 */
			image: () => LocalizedString
			mainNewsOfTheEdition: {
				/**
				 * Main news of the edition
				 */
				mainNewsOfTheEdition: () => LocalizedString
				/**
				 * The platform's algorithm will choose only one news to be the biggest highlight of the newspaper's cover. Answer "<b>Yes</b>" if your news is a "<b>Breaking News</b>" and you want it to be considered the main news.
				 */
				mainNewsOfTheEditionMessage: () => LocalizedString
				/**
				 * No! This news will not be the main
				 */
				notTheMainNews: () => LocalizedString
				/**
				 * Yes! Take this news into consideration
				 */
				yesTheMainNews: () => LocalizedString
			}
			category: {
				/**
				 * Other
				 */
				other: () => LocalizedString
				/**
				 * Category
				 */
				category: () => LocalizedString
				/**
				 * Sports
				 */
				sports: () => LocalizedString
				/**
				 * Memories
				 */
				memories: () => LocalizedString
				/**
				 * Books
				 */
				books: () => LocalizedString
				/**
				 * Gastronomy
				 */
				gastronomy: () => LocalizedString
				/**
				 * Series
				 */
				series: () => LocalizedString
				/**
				 * Movies
				 */
				movies: () => LocalizedString
				/**
				 * Music
				 */
				music: () => LocalizedString
				/**
				 * Food
				 */
				food: () => LocalizedString
				/**
				 * Culture
				 */
				culture: () => LocalizedString
				/**
				 * Health
				 */
				health: () => LocalizedString
				/**
				 * Tourism
				 */
				tourism: () => LocalizedString
				/**
				 * Crime
				 */
				crime: () => LocalizedString
				/**
				 * Science
				 */
				science: () => LocalizedString
				/**
				 * Technology
				 */
				technology: () => LocalizedString
				/**
				 * Business
				 */
				business: () => LocalizedString
				/**
				 * Economy
				 */
				economy: () => LocalizedString
				/**
				 * Politics
				 */
				politics: () => LocalizedString
				/**
				 * Humor
				 */
				humor: () => LocalizedString
				/**
				 * Meteorology
				 */
				meteorology: () => LocalizedString
			}
			feeling: {
				/**
				 * Outro
				 */
				other: () => LocalizedString
				/**
				 * Celebrant
				 */
				celebrant: () => LocalizedString
				/**
				 * Passionate
				 */
				passionate: () => LocalizedString
				/**
				 * Happy
				 */
				happy: () => LocalizedString
				/**
				 * Funny
				 */
				funny: () => LocalizedString
				/**
				 * Cool
				 */
				cool: () => LocalizedString
				/**
				 * Silly
				 */
				silly: () => LocalizedString
				/**
				 * Excited
				 */
				excited: () => LocalizedString
				/**
				 * Energized
				 */
				energized: () => LocalizedString
				/**
				 * Powerful
				 */
				powerful: () => LocalizedString
				/**
				 * Peaceful
				 */
				peaceful: () => LocalizedString
				/**
				 * Optimistic
				 */
				optimistic: () => LocalizedString
				/**
				 * Thankful
				 */
				thankful: () => LocalizedString
				/**
				 * Sensitive
				 */
				sensitive: () => LocalizedString
				/**
				 * Calm
				 */
				calm: () => LocalizedString
				/**
				 * Anxious
				 */
				anxious: () => LocalizedString
				/**
				 * Sad
				 */
				sad: () => LocalizedString
				/**
				 * Disappointed
				 */
				disappointed: () => LocalizedString
				/**
				 * Angry
				 */
				angry: () => LocalizedString
				/**
				 * Proud
				 */
				proud: () => LocalizedString
				/**
				 * Surprised
				 */
				surprised: () => LocalizedString
				/**
				 * Shocked
				 */
				shocked: () => LocalizedString
				/**
				 * Confused
				 */
				confused: () => LocalizedString
				/**
				 * Scared
				 */
				scared: () => LocalizedString
				/**
				 * Bored
				 */
				bored: () => LocalizedString
				/**
				 * Sick
				 */
				sick: () => LocalizedString
				/**
				 * Seasick
				 */
				seasick: () => LocalizedString
				/**
				 * Jealous
				 */
				jealous: () => LocalizedString
				/**
				 * Curious
				 */
				curious: () => LocalizedString
				/**
				 * Embarrassed
				 */
				embarrassed: () => LocalizedString
				/**
				 * Kind
				 */
				kind: () => LocalizedString
				/**
				 * Alert
				 */
				alert: () => LocalizedString
				/**
				 * Investigative
				 */
				investigative: () => LocalizedString
			}
			newsType: {
				/**
				 * Feeling
				 */
				newsType: () => LocalizedString
				/**
				 * Choose the feeling that the content of this news fits or conveys to those who read it.
				 */
				newsTypeMessage: () => LocalizedString
			}
			contentCharacteristics: {
				/**
				 * Content characteristics
				 */
				contentCharacteristics: () => LocalizedString
				/**
				 * Check all the options that characterize the news content.
				 */
				contentCharacteristicsMessage: () => LocalizedString
				/**
				 * Inappropriate for underage
				 */
				inappropriateForUnderage: () => LocalizedString
				/**
				 * A platform member is mentioned
				 */
				aPlatformMemberIsMentioned: () => LocalizedString
				/**
				 * The protagonist is a member of the platform
				 */
				theProtagonistIsAMemberOfThePlatform: () => LocalizedString
			}
			whenWillBePublished: {
				/**
				 * When will the news be published?
				 */
				whenWillBePublished: () => LocalizedString
				/**
				 * Save to drafts and do not publish
				 */
				saveToDrafts: () => LocalizedString
				/**
				 * July 5, 2022 edition (next)
				 */
				nextEdition: () => LocalizedString
				/**
				 * August 14, 2022 edition
				 */
				afterNextEdition: () => LocalizedString
			}
			shortDescription: {
				/**
				 * Short description
				 */
				shortDescription: () => LocalizedString
				/**
				 * This description may appear on the front page of the newspaper with the title of the news.
				 */
				shortDescriptionMessage: () => LocalizedString
				/**
				 * characters typed out of {maxNumber} allowed
				 */
				charactersTypedMessage: (arg: { maxNumber: number }) => LocalizedString
			}
			/**
			 * Content
			 */
			content: () => LocalizedString
			/**
			 * Create news
			 */
			createNews: () => LocalizedString
			/**
			 * News created
			 */
			newsCreated: () => LocalizedString
			/**
			 * Your news has been created successfully
			 */
			newsCreatedMessage: () => LocalizedString
		}
		newsReader: {
			/**
			 * WARNING
			 */
			warning: () => LocalizedString
			/**
			 * The news website you are being redirected to often reports <b>APPEALING NEWS</b> and lacks the truth, so <b>IT SHOULD NOT BE SEEN</b> by anyone.
			 */
			warningMessage: () => LocalizedString
			/**
			 * Edition
			 */
			edition: () => LocalizedString
			/**
			 * Redirecting in
			 */
			redirectingIn: () => LocalizedString
			/**
			 * Posted on June 15, 2022
			 */
			postDate: () => LocalizedString
			/**
			 * Go to platform
			 */
			goToPlatform: () => LocalizedString
			/**
			 * By
			 */
			by: () => LocalizedString
			example1: {
				/**
				 * <b>T</b>his page is <b>just an example to illustrate the idea</b>, but the final app will not use the technologies used here, nor will it have the same look.
				 */
				part1: () => LocalizedString
				/**
				 * <b>T</b>he idea of this page is to create a website that looks similar to
				 */
				part2A: () => LocalizedString
				/**
				 * from the Harry Potter saga.
				 */
				part2B: () => LocalizedString
				/**
				 * <b>T</b>he website is intended to be used in a <b>digital panel</b> on the wall, and framed like a painting.
				 */
				part3: () => LocalizedString
				/**
				 * <b>T</b>he current version is not mobile friendly, as it was created quickly just to exemplify the idea, but the final version could be.
				 */
				part4: () => LocalizedString
				/**
				 * <b>T</b>he website will have many formatting features and visual effects that can be configured by the news authors.
				 */
				part5: () => LocalizedString
				/**
				 * <b>T</b>he page will be hosted on its own domain, but will share the same backend as the main platform.
				 */
				part6: () => LocalizedString
			}
			example2: {
				/**
				 * WHAT WILL THE CHILD BE CALLED?
				 */
				title: () => LocalizedString
				/**
				 * <b>I</b> have just published a poll on the platform, where you can suggest the name of John's and mine's son. If the name you suggested is chosen, in addition to the honor of this choice, you will also win a <b>super gift</b>!
				 */
				part1: () => LocalizedString
				/**
				 * <b>G</b>olden tip! Research the origin of the name before posting your suggestion. The meaning of the name is very important for parents.
				 */
				part2: () => LocalizedString
				/**
				 * <b>N</b>ames whose meaning is <b>related to the sea</b> will be very well seen, as the parents are surfers, half hippies, and love the sea and nature.
				 */
				part3: () => LocalizedString
				/**
				 * THE 2º PLACE
				 */
				part4SubTitle: () => LocalizedString
				/**
				 * <b>T</b>he person who suggests the second name that the parents like the most will also be awarded!
				 */
				part4: () => LocalizedString
				/**
				 * <b>T</b>he second place award will consist of a <b>two-week trip to the Falklands Islands</b>.
				 */
				part5: () => LocalizedString
				/**
				 * <b>A</b>ll those who answer the poll on the platform, and guess the gender of our baby, will also win a nice award.
				 */
				part6: () => LocalizedString
				/**
				 * <b>T</b>his award will be simple, surprise, but VERY useful!
				 */
				part7: () => LocalizedString
				/**
				 * BOY OR GIRL?
				 */
				verticalTitle: () => LocalizedString
			}
			example2B: {
				/**
				 * June 15, 2022
				 */
				date: () => LocalizedString
				/**
				 * What will the child be called?
				 */
				title: () => LocalizedString
				/**
				 * I have just published a poll on the platform, where you can suggest the name of John's and mine's son. If the name you suggested is chosen, in addition to the honor of this choice, you will also win a <b>super gift</b>!
				 */
				part1: () => LocalizedString
				/**
				 * Golden tip! Research the origin of the name before posting your suggestion. The meaning of the name is very important for parents.
				 */
				part2: () => LocalizedString
				/**
				 * Names whose meaning is <b>related to the sea</b> will be very well seen, as the parents are surfers, half hippies, and love the sea and nature.
				 */
				part3: () => LocalizedString
				/**
				 * The 2º place
				 */
				part4SubTitle: () => LocalizedString
				/**
				 * The person who suggests the second name that the parents like the most will also be awarded!
				 */
				part4: () => LocalizedString
				/**
				 * The second place award will consist of a <b>two-week trip to the Falklands Islands</b>.
				 */
				part5: () => LocalizedString
				/**
				 * Boy or girl?
				 */
				part6SubTitle: () => LocalizedString
				/**
				 * All those who answer the poll on the platform, and guess the gender of our baby, will also win a nice award.
				 */
				part6: () => LocalizedString
				/**
				 * This award will be simple, surprise, but VERY useful!
				 */
				part7: () => LocalizedString
			}
		}
	}
	platformSettings: {
		/**
		 * Platform settings
		 */
		platformSettings: () => LocalizedString
		generalSection: {
			/**
			 * General
			 */
			menu: () => LocalizedString
			/**
			 * Platform settings
			 */
			title: () => LocalizedString
			/**
			 * This settings section is only visible to the accounts of <b>admin members</b> who are considered to be <b>mature age</b>.
			 */
			message: () => LocalizedString
			/**
			 * Age of a mature member
			 */
			ageOfAMatureMember: () => LocalizedString
			/**
			 * Set the minimum age for a member to be considered a mature person, and thus receive administrative privileges on the platform.
			 */
			ageOfAMatureMemberMessage: () => LocalizedString
			/**
			 * years
			 */
			years: () => LocalizedString
		}
		newAccountSection: {
			/**
			 * New account
			 */
			menu: () => LocalizedString
			/**
			 * New account
			 */
			title: () => LocalizedString
			/**
			 * Configure everything related to creating new member and guest accounts.
			 */
			message: () => LocalizedString
			/**
			 * How are new user accounts created?
			 */
			howAreNewUserAccountsCreated: () => LocalizedString
			/**
			 * By member invitation only
			 */
			byMemberInvitationOnly: () => LocalizedString
			/**
			 * Public registration page
			 */
			publicRegistrationPage: () => LocalizedString
			/**
			 * New registrations disabled
			 */
			newRegistrationsDisabled: () => LocalizedString
			/**
			 * Who can send invitations to new member accounts?
			 */
			whoCanSendInvitationsToNewMemberAccounts: () => LocalizedString
			/**
			 * Admin members, of mature age
			 */
			adminMembersOfMatureAge: () => LocalizedString
			/**
			 * Admin members
			 */
			adminMembers: () => LocalizedString
			/**
			 * Who can send invitations to new guest accounts?
			 */
			whoCanSendInvitationsToNewGuestAccounts: () => LocalizedString
		}
		guestsSection: {
			/**
			 * Guests
			 */
			menu: () => LocalizedString
			/**
			 * Guests
			 */
			title: () => LocalizedString
			/**
			 * Manage guest user account privileges here.
			 */
			message: () => LocalizedString
			/**
			 * Features enabled for guest accounts
			 */
			featuresEnabled: () => LocalizedString
			/**
			 * Feedback submission
			 */
			feedbackSubmission: () => LocalizedString
			/**
			 * Polls with guest-enabled content
			 */
			pollsWithGuestEnabledContent: () => LocalizedString
			/**
			 * Topics with guest-enabled content
			 */
			topicsWithGuestEnabledContent: () => LocalizedString
			/**
			 * News with guest-enabled content
			 */
			newsWithGuestEnabledContent: () => LocalizedString
		}
		feedbackSection: {
			/**
			 * Feedback
			 */
			menu: () => LocalizedString
			/**
			 * Feedback
			 */
			title: () => LocalizedString
			message: () => LocalizedString
		}
		pollsSection: {
			/**
			 * Polls
			 */
			menu: () => LocalizedString
			/**
			 * Polls
			 */
			title: () => LocalizedString
			/**
			 * Configure everything related to platform polls.
			 */
			message: () => LocalizedString
			/**
			 * Maximum number of polls per month
			 */
			maximumNumberOfPolls: () => LocalizedString
			/**
			 * Set the maximum number of polls that can be created per month on the platform. The amount must be the total value of each user's polls added together.
			 */
			maximumNumberOfPollsMessage: () => LocalizedString
		}
		topicsSection: {
			/**
			 * Topics
			 */
			menu: () => LocalizedString
			/**
			 * Topics
			 */
			title: () => LocalizedString
			/**
			 * Configure everything related to the platform topics.
			 */
			message: () => LocalizedString
			/**
			 * Chat rooms on topics
			 */
			chatRoomsOnTopics: () => LocalizedString
			/**
			 * Configure whether within each topic there will be a chat room related to the subject of the same topic.
			 */
			chatRoomsOnTopicsMessage: () => LocalizedString
			/**
			 * Enable chat room within topics
			 */
			enableChatRoomWithinTopics: () => LocalizedString
			/**
			 * Disable chatroom on topics
			 */
			disableChatroomOnTopics: () => LocalizedString
		}
		newsReaderSection: {
			/**
			 * Newspaper
			 */
			menu: () => LocalizedString
			/**
			 * Group newspaper
			 */
			title: () => LocalizedString
			message: () => LocalizedString
			/**
			 * Newspaper name
			 */
			newspaperName: () => LocalizedString
			/**
			 * Newspaper link
			 */
			newspaperLink: () => LocalizedString
			/**
			 * Periodicity of the newspaper edition
			 */
			periodicityOfTheNewspaper: () => LocalizedString
			/**
			 * Configure how many days it takes for a new edition to be published.
			 */
			periodicityOfTheNewspaperMessage: () => LocalizedString
			/**
			 * days
			 */
			days: () => LocalizedString
		}
	}
	polls: {
		exampleOne: {
			/**
			 * What will be the name of Jane and Joe's baby?
			 */
			title: () => LocalizedString
			/**
			 * In this poll you can suggest the name of my son and John. If the name you suggested is chosen, in addition to the honor of that choice, you will also receive an <b>amazing surprise gift</b>! 🎉
			 */
			message: () => LocalizedString
		}
		exampleTwo: {
			/**
			 * Will Jane and Joe's baby be a boy or a girl?
			 */
			title: () => LocalizedString
			/**
			 * I created this poll for you to try to guess if my and John's child will be a boy or a girl. Everyone who answered correctly received a gift.
			 */
			message: () => LocalizedString
		}
		/**
		 * Polls
		 */
		polls: () => LocalizedString
		/**
		 * Poll management
		 */
		pollManagement: () => LocalizedString
		/**
		 * In this section you can answer other users' polls, create your own polls and access the results.
		 */
		pollManagementMessage: () => LocalizedString
		/**
		 * Create poll
		 */
		createPoll: () => LocalizedString
		/**
		 * View all polls
		 */
		viewAllPolls: () => LocalizedString
		/**
		 * View only active polls
		 */
		viewOnlyActivePolls: () => LocalizedString
		/**
		 * All polls
		 */
		allPolls: () => LocalizedString
		/**
		 * Active polls
		 */
		activePolls: () => LocalizedString
		/**
		 * ✔ Answered
		 */
		answered: () => LocalizedString
		/**
		 * ✔ Unanswered
		 */
		unanswered: () => LocalizedString
		/**
		 * Name suggestion
		 */
		nameSuggestion: () => LocalizedString
		/**
		 * Name meaning
		 */
		nameMeaning: () => LocalizedString
		/**
		 * Name gender
		 */
		nameGender: () => LocalizedString
		/**
		 * Male
		 */
		male: () => LocalizedString
		/**
		 * Feminine
		 */
		feminine: () => LocalizedString
		/**
		 * Unisex
		 */
		unisex: () => LocalizedString
		/**
		 * Answer poll
		 */
		answerPoll: () => LocalizedString
		/**
		 * Poll answered 🎉
		 */
		pollAnswered: () => LocalizedString
		/**
		 * Within a week all answers will be published
		 */
		pollAnsweredMessage: () => LocalizedString
		/**
		 * What do you want to do now?
		 */
		whatDoYouWantToDoNow: () => LocalizedString
		/**
		 * Go to polls
		 */
		goToPolls: () => LocalizedString
		/**
		 * Go to home page
		 */
		goToHomePage: () => LocalizedString
		/**
		 * ANSWERS
		 */
		answers: () => LocalizedString
		/**
		 * Girl
		 */
		girl: () => LocalizedString
		/**
		 * Boy
		 */
		boy: () => LocalizedString
		/**
		 * People who responded
		 */
		peopleWhoResponded: () => LocalizedString
		/**
		 * Poll title
		 */
		pollTitle: () => LocalizedString
		/**
		 * Question
		 */
		question: () => LocalizedString
		/**
		 * Poll created
		 */
		pollCreated: () => LocalizedString
		/**
		 * Your poll was created successfully
		 */
		pollCreatedMessage: () => LocalizedString
		/**
		 * Poll closed
		 */
		pollClosed: () => LocalizedString
	}
	profiles: {
		/**
		 * Profiles
		 */
		profiles: () => LocalizedString
		/**
		 * User profile
		 */
		userProfile: () => LocalizedString
		/**
		 * Users
		 */
		users: () => LocalizedString
		/**
		 * Platform users
		 */
		platformUsers: () => LocalizedString
		warning: {
			/**
			 * There is only one example of a user profile on the platform, the following:
			 */
			onlyOneExemple: () => LocalizedString
			/**
			 * Would you like to open this example?
			 */
			wouldYouLikeToOpenThisExample: () => LocalizedString
			/**
			 * Open the example
			 */
			openTheExample: () => LocalizedString
			/**
			 * Do not open
			 */
			doNotOpen: () => LocalizedString
		}
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Full name
		 */
		fullName: () => LocalizedString
		/**
		 * Short name
		 */
		shortName: () => LocalizedString
		/**
		 * Nickname
		 */
		nickname: () => LocalizedString
		/**
		 * Account
		 */
		account: () => LocalizedString
		/**
		 * Birth date
		 */
		birthDate: () => LocalizedString
		/**
		 * Age
		 */
		age: () => LocalizedString
		/**
		 * years
		 */
		years: () => LocalizedString
		/**
		 * Useful links
		 */
		usefulLinks: () => LocalizedString
		/**
		 * Edit this profile data
		 */
		editUserData: () => LocalizedString
		/**
		 * See other users profiles
		 */
		goToOtherProfiles: () => LocalizedString
		/**
		 * Learn more about account types
		 */
		goToAccountTypes: () => LocalizedString
	}
	signIn: {
		/**
		 * Sign in
		 */
		signIn: () => LocalizedString
		/**
		 * Nickname or email
		 */
		nicknameOrEmail: () => LocalizedString
		/**
		 * Nickname
		 */
		nickname: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * If you are not a user,
		 */
		invitationPart1: () => LocalizedString
		/**
		 * request an invitation
		 */
		invitationPart2: () => LocalizedString
	}
	signUp: {
		requirements: {
			/**
			 * Requirements
			 */
			requirements: () => LocalizedString
			/**
			 * Sign up requirements
			 */
			signUpRequirements: () => LocalizedString
			/**
			 * About
			 */
			about: () => LocalizedString
			/**
			 * Pending
			 */
			pending: () => LocalizedString
			/**
			 * Completed
			 */
			completed: () => LocalizedString
			/**
			 * Almost done!
			 */
			almostDone: () => LocalizedString
			/**
			 * Your account is currently in <b>pre-registration</b> status. It is still necessary to complete some prerequisites for you to be able to access the platform. Click on the <b>Pending</b> tab to view your open tasks.
			 */
			aboutMessage: () => LocalizedString
			/**
			 * Pending tasks
			 */
			pendingTasks: () => LocalizedString
			/**
			 * You have <b>1</b> pending task.
			 */
			pendingTaskWarning: () => LocalizedString
			pendingTasksItem: {
				/**
				 * User data confirmation
				 */
				userDataConfirmation: () => LocalizedString
			}
			/**
			 * Task history
			 */
			taskHistory: () => LocalizedString
			/**
			 * today
			 */
			today: () => LocalizedString
			completedTaskItem: {
				/**
				 * Default language changed.
				 */
				defaultLanguageChanged: () => LocalizedString
				/**
				 * Profile image uploaded.
				 */
				profileImageUploaded: () => LocalizedString
				/**
				 * Chosen interface visual theme.
				 */
				chosenInterfaceVisualTheme: () => LocalizedString
				/**
				 * Email <b>johndoe@gmail.com</b> has been confirmed.
				 */
				emailConfirmed: () => LocalizedString
				/**
				 * Defined the nickname: <b>@john</b>
				 */
				nicknameDefined: () => LocalizedString
				/**
				 * Access password changed.
				 */
				passwordChanged: () => LocalizedString
				/**
				 * Member invitation has been approved.
				 */
				memberInvitationApproved: () => LocalizedString
				/**
				 * You have requested an invitation to be a platform member.
				 */
				memberInvitationRequested: () => LocalizedString
			}
			dataConfirmation: {
				/**
				 * Data confirmation
				 */
				dataConfirmation: () => LocalizedString
				/**
				 * Review your data
				 */
				reviewYourData: () => LocalizedString
				/**
				 * Below are the data filled in during your user pre-registration, so you can review them.
				 */
				dataConfirmationSectionMessage: () => LocalizedString
				fields: {
					/**
					 * Name
					 */
					name: () => LocalizedString
					/**
					 * Email
					 */
					email: () => LocalizedString
					/**
					 * Nickname
					 */
					nickname: () => LocalizedString
					/**
					 * Theme
					 */
					theme: () => LocalizedString
					/**
					 * Language
					 */
					language: () => LocalizedString
					/**
					 * Profile image
					 */
					profileImage: () => LocalizedString
				}
				/**
				 * Click <b>Confirm data</b> if all the data above is correct.
				 */
				confirmDataMessage: () => LocalizedString
				/**
				 * Confirm data
				 */
				confirmData: () => LocalizedString
			}
		}
		welcome: {
			/**
			 * Welcome!
			 */
			welcome: () => LocalizedString
			/**
			 * You are the newest member of the platform.
			 */
			youAreTheNewestMember: () => LocalizedString
			/**
			 * Your registration has been successfully completed and you are now the newest member of the platform. Click the button below to be redirected to the home page.
			 */
			welcomeMessage: () => LocalizedString
			/**
			 * Go to the home page
			 */
			goToTheHomePage: () => LocalizedString
		}
	}
	topics: {
		exampleOne: {
			/**
			 * Visual identity of the Doe Family
			 */
			title: () => LocalizedString
		}
		exampleTwo: {
			/**
			 * Create your own digital news panel
			 */
			title: () => LocalizedString
		}
		exampleThree: {
			/**
			 * About the Doe Family website
			 */
			title: () => LocalizedString
		}
		/**
		 * Topics
		 */
		topics: () => LocalizedString
		/**
		 * Platform member topics
		 */
		groupTopics: () => LocalizedString
		/**
		 * In this platform section you can create and manage "topics". And a “topic” consists of a group of pages with shared editing, with all pages related to the same central subject.
		 */
		groupTopicsMessage: () => LocalizedString
		/**
		 * Existing topics
		 */
		existingTopics: () => LocalizedString
		example: {
			/**
			 * Intro
			 */
			intro: () => LocalizedString
			/**
			 * Visual identity of the Doe Family
			 */
			topicTitle: () => LocalizedString
			/**
			 * Page
			 */
			page: () => LocalizedString
			/**
			 * In this topic everything is related to the visual identity of the Doe Family. For example: the history of the family coat of arms; downloadable images and files; etc.
			 */
			introMessage: () => LocalizedString
			/**
			 * This is an example of a topic created by a member of the platform. A "topic" consists of a set of pages related to a central theme.
			 */
			warningMessage: () => LocalizedString
			/**
			 * Coat of arms
			 */
			coatOfArms: () => LocalizedString
			/**
			 * Doe Family coat of arms
			 */
			doeFamilyCoatOfArms: () => LocalizedString
			/**
			 * Traditional coat of arms
			 */
			traditionalCoatOfArms: () => LocalizedString
			/**
			 * This is a reinterpretation of the old Doe Family coat of arms. This coat of arms is versatile and can be used in almost any context.
			 */
			traditionalCoatOfArmsMessage: () => LocalizedString
			/**
			 * Fun coat of arms
			 */
			funCoatOfArms: () => LocalizedString
			/**
			 * This is a lively colored coat of arms and was created to be used in fun contexts such as parties and recreational events.
			 */
			funCoatOfArmsMessage: () => LocalizedString
			/**
			 * Mourning coat of arms
			 */
			mourningCoatOfArms: () => LocalizedString
			/**
			 * This is a coat of arms with sober colors to be used in mourning circumstances.
			 */
			mourningCoatOfArmsMessage: () => LocalizedString
			/**
			 * This is another example of a page created within the topic by one of the platform's members. Because any member can create pages within the topics created by other members.
			 */
			anotherPageMessage: () => LocalizedString
			/**
			 * today at 3 am
			 */
			chatMessageDate: () => LocalizedString
			/**
			 * Example of message sent
			 */
			chatMessage: () => LocalizedString
			/**
			 * Place to write messages
			 */
			placeToWriteMessages: () => LocalizedString
		}
		warningMessage: {
			/**
			 * This is an incomplete example. Other subpages and functionality will be implemented.
			 */
			incompleteExample: () => LocalizedString
			/**
			 * There is only one topic example on the platform, the following:
			 */
			onlyOneExample: () => LocalizedString
			/**
			 * Would you like to open this example?
			 */
			wouldYouLikeToOpenThisExample: () => LocalizedString
			/**
			 * Open the example
			 */
			openTheExample: () => LocalizedString
			/**
			 * Do not open
			 */
			doNotOpen: () => LocalizedString
		}
		/**
		 * back
		 */
		back: () => LocalizedString
	}
	userSettings: {
		/**
		 * Settings
		 */
		userSettings: () => LocalizedString
		menu: {
			/**
			 * General
			 */
			general: () => LocalizedString
			/**
			 * Profile image
			 */
			profileImage: () => LocalizedString
			/**
			 * Theme
			 */
			theme: () => LocalizedString
		}
		/**
		 * Account settings
		 */
		generalSettings: () => LocalizedString
		/**
		 * Configure your user profile data here.
		 */
		generalSettingsMessage: () => LocalizedString
		/**
		 * Profile image
		 */
		profileImage: () => LocalizedString
		/**
		 * Upload an image to your user profile.
		 */
		profileImageMessage: () => LocalizedString
		/**
		 * Theme
		 */
		theme: () => LocalizedString
		/**
		 * Full name
		 */
		fullName: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * Birth date
		 */
		birthDate: () => LocalizedString
	}
}

export type Formatters = {}
